{
  "swagger": "2.0",
  "info": {
    "title": "v1/market.proto",
    "version": "1.0"
  },
  "tags": [
    {
      "name": "Public"
    },
    {
      "name": "Private"
    }
  ],
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/user/balance": {
      "get": {
        "summary": "Получение текущего баланса пользователя",
        "description": "Хендлер доступен только авторизованному пользователю. В ответе должны содержаться данные о текущей сумме баллов лояльности, а также сумме использованных за весь период регистрации баллов.",
        "operationId": "Private_GetBalance",
        "responses": {
          "200": {
            "description": "успешная обработка запроса.",
            "schema": {
              "$ref": "#/definitions/v1Balance"
            },
            "examples": {
              "application/json": {
                "current": 500.5,
                "withdrawn": 42
              }
            }
          },
          "401": {
            "description": "пользователь не авторизован.",
            "schema": {}
          },
          "500": {
            "description": "внутренняя ошибка сервера.",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "message",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Private"
        ],
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/api/user/balance/withdraw": {
      "post": {
        "summary": "Запрос на списание средств",
        "description": "Хендлер доступен только авторизованному пользователю. Номер заказа представляет собой гипотетический номер нового заказа пользователя, в счёт оплаты которого списываются баллы.",
        "operationId": "Private_BalanceWithdraw",
        "responses": {
          "200": {
            "description": "успешная обработка запроса",
            "schema": {
              "$ref": "#/definitions/v1Empty"
            }
          },
          "401": {
            "description": "пользователь не авторизован",
            "schema": {}
          },
          "402": {
            "description": "на счету недостаточно средств",
            "schema": {}
          },
          "422": {
            "description": "неверный номер заказа",
            "schema": {}
          },
          "500": {
            "description": "внутренняя ошибка сервера",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1WithdrawRequest"
            }
          }
        ],
        "tags": [
          "Private"
        ],
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/api/user/balance/withdrawals": {
      "get": {
        "summary": "Получение информации о выводе средств",
        "description": "Хендлер доступен только авторизованному пользователю. Факты выводов в выдаче должны быть отсортированы по времени вывода от самых старых к самым новым. Формат даты — RFC3339.",
        "operationId": "Private_GetWithdrawals",
        "responses": {
          "200": {
            "description": "успешная обработка запроса.",
            "schema": {
              "$ref": "#/definitions/v1WithdrawsResponse"
            },
            "examples": {
              "application/json": [
                {
                  "order": "2377225624",
                  "sum": 500,
                  "processed_at": "2020-12-09T16:09:57+03:00"
                }
              ]
            }
          },
          "204": {
            "description": "нет ни одного списания.",
            "schema": {}
          },
          "401": {
            "description": "пользователь не авторизован.",
            "schema": {}
          },
          "500": {
            "description": "внутренняя ошибка сервера.",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "message",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Private"
        ],
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/api/user/login": {
      "post": {
        "summary": "Аутентификация пользователя",
        "description": "Аутентификация производится по паре логин/пароль.",
        "operationId": "Public_UsersLogin",
        "responses": {
          "200": {
            "description": "пользователь успешно аутентифицирован",
            "schema": {
              "$ref": "#/definitions/v1Empty"
            }
          },
          "400": {
            "description": "неверный формат запроса",
            "schema": {}
          },
          "401": {
            "description": "неверная пара логин/пароль",
            "schema": {}
          },
          "500": {
            "description": "внутренняя ошибка сервера",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1AuthRequest"
            }
          }
        ],
        "tags": [
          "Public"
        ]
      }
    },
    "/api/user/orders": {
      "get": {
        "summary": "Получение списка загруженных номеров заказов",
        "description": "Хендлер доступен только авторизованному пользователю. Номера заказа в выдаче должны быть отсортированы по времени загрузки от самых старых к самым новым. Формат даты — RFC3339.",
        "operationId": "Private_OrdersGet",
        "responses": {
          "200": {
            "description": "успешная обработка запроса",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/v1Order"
              }
            },
            "examples": {
              "application/json": [
                {
                  "number": "9278923470",
                  "status": "PROCESSED",
                  "accrual": 500,
                  "uploaded_at": "2020-12-10T15:15:45+03:00"
                },
                {
                  "number": "12345678903",
                  "status": "PROCESSING",
                  "uploaded_at": "2020-12-10T15:12:01+03:00"
                },
                {
                  "number": "346436439",
                  "status": "INVALID",
                  "uploaded_at": "2020-12-09T16:09:53+03:00"
                }
              ]
            }
          },
          "204": {
            "description": "нет данных для ответа",
            "schema": {}
          },
          "401": {
            "description": "пользователь не авторизован",
            "schema": {}
          },
          "500": {
            "description": "внутренняя ошибка сервера",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "message",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Private"
        ],
        "security": [
          {
            "authorization": []
          }
        ]
      },
      "post": {
        "summary": "Загрузка номера заказа",
        "description": "Хендлер доступен только аутентифицированным пользователям. Номером заказа является последовательность цифр произвольной длины.Номер заказа может быть проверен на корректность ввода с помощью алгоритма Луна.",
        "operationId": "Private_OrdersAdd",
        "responses": {
          "200": {
            "description": "номер заказа уже был загружен этим пользователем",
            "schema": {
              "$ref": "#/definitions/v1Empty"
            }
          },
          "202": {
            "description": "новый номер заказа принят в обработку",
            "schema": {}
          },
          "400": {
            "description": "неверный формат запроса",
            "schema": {}
          },
          "401": {
            "description": "пользователь не аутентифицирован",
            "schema": {}
          },
          "409": {
            "description": "номер заказа уже был загружен другим пользователем",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "Order",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "format": "int64"
            }
          }
        ],
        "tags": [
          "Private"
        ],
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/api/user/register": {
      "post": {
        "summary": "Регистрация пользователя",
        "description": "Регистрация производится по паре логин/пароль. Каждый логин должен быть уникальным. После успешной регистрации должна происходить автоматическая аутентификация пользователя.",
        "operationId": "Public_UsersRegister",
        "responses": {
          "200": {
            "description": "пользователь успешно зарегистрирован и аутентифицирован",
            "schema": {
              "$ref": "#/definitions/v1Empty"
            }
          },
          "400": {
            "description": "неверный формат запроса",
            "schema": {}
          },
          "409": {
            "description": "логин уже занят",
            "schema": {}
          },
          "500": {
            "description": "внутренняя ошибка сервера",
            "schema": {}
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1AuthRequest"
            }
          }
        ],
        "tags": [
          "Public"
        ]
      }
    }
  },
  "definitions": {
    "googlerpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "v1AuthRequest": {
      "type": "object",
      "example": {
        "login": "\u003clogin\u003e",
        "password": "\u003cpassword\u003e"
      },
      "properties": {
        "login": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "description": "Запрос на регистрацию или аутентификацию",
      "title": "AuthRequest",
      "required": [
        "login",
        "password"
      ]
    },
    "v1Balance": {
      "type": "object",
      "properties": {
        "current": {
          "type": "number",
          "format": "double"
        },
        "withdrawn": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "v1Empty": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "v1Order": {
      "type": "object",
      "example": {
        "number": "9278923470",
        "status": "PROCESSED",
        "accrual": 500,
        "uploaded_at": "2020-12-10T15:15:45+03:00"
      },
      "properties": {
        "number": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/v1OrderStatus"
        },
        "accrual": {
          "type": "number",
          "format": "double"
        },
        "uploadedAt": {
          "type": "string"
        }
      }
    },
    "v1OrderStatus": {
      "type": "string",
      "enum": [
        "REGISTERED",
        "INVALID",
        "PROCESSING",
        "PROCESSED"
      ],
      "default": "REGISTERED"
    },
    "v1OrdersResponse": {
      "type": "object",
      "example": [
        {
          "number": "9278923470",
          "status": "PROCESSED",
          "accrual": 500,
          "uploaded_at": "2020-12-10T15:15:45+03:00"
        },
        {
          "number": "12345678903",
          "status": "PROCESSING",
          "uploaded_at": "2020-12-10T15:12:01+03:00"
        },
        {
          "number": "346436439",
          "status": "INVALID",
          "uploaded_at": "2020-12-09T16:09:53+03:00"
        }
      ],
      "properties": {
        "orders": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1Order"
          }
        }
      }
    },
    "v1WithdrawRequest": {
      "type": "object",
      "properties": {
        "order": {
          "type": "string"
        },
        "sum": {
          "type": "string",
          "format": "int64"
        },
        "processedAt": {
          "type": "string"
        }
      }
    },
    "v1WithdrawsResponse": {
      "type": "object",
      "properties": {
        "withdraws": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1WithdrawRequest"
          }
        }
      }
    }
  },
  "externalDocs": {
    "description": "gophermart магазинчик",
    "url": "https://github.com/gopherlearning/gophermart"
  }
}
